/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as BattleMapsRouteImport } from './routes/battle-maps'
import { Route as IndexRouteImport } from './routes/index'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleMapsRoute = BattleMapsRouteImport.update({
  id: '/battle-maps',
  path: '/battle-maps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle-maps': typeof BattleMapsRoute
  '/worlds': typeof WorldsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle-maps': typeof BattleMapsRoute
  '/worlds': typeof WorldsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battle-maps': typeof BattleMapsRoute
  '/worlds': typeof WorldsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/battle-maps' | '/worlds'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/battle-maps' | '/worlds'
  id: '__root__' | '/' | '/battle-maps' | '/worlds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleMapsRoute: typeof BattleMapsRoute
  WorldsRoute: typeof WorldsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-maps': {
      id: '/battle-maps'
      path: '/battle-maps'
      fullPath: '/battle-maps'
      preLoaderRoute: typeof BattleMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleMapsRoute: BattleMapsRoute,
  WorldsRoute: WorldsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
